spring:
  datasource:
    url: jdbc:mysql://192.168.13.54:3306/scms_admin
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.scms.learn.mybatis.model
